### ISSUE TITLE
Provide __version__ attribute

### ISSUE THREAD

**Issue by shoyer** [ecmwf/cfgrib#31]
It's a convention for Python projects to set the `__version__` attribute to a string representing the current version. This facilitates debugging and version checking by downstream projects (e.g., [xarray](https://github.com/pydata/xarray/pull/2555)).

**Comment by alexamici** [comment]
@shoyer I'm using [zest.releaser](https://zestreleaser.readthedocs.io/en/stable/) for version management and [they suggest](https://zestreleaser.readthedocs.io/en/stable/versions.html#using-the-version-number-in-setup-py-or-setup-cfg-as-version) adding this snippet to `cfgrib/__init__.py`:
```
import pkg_resources

__version__ = pkg_resources.get_distribution('cfgib').version
```
in order to still keep one single master version in `setup.py`. Would that work for you?

**Comment by alexamici** [comment]
Ok, things got a bit more complicated than that, but now `cfgrib.__version__` return the currently installed version.

**Comment by alexamici** [comment]
That was too fast. Current `master` has a circular import problem that prevents setting `__version__`.

**Comment by shoyer** [comment]
versioneer is one commonly used tool for this: https://github.com/warner/python-versioneer

(We use it in xarray, pandas and dask)

**Comment by alexamici** [comment]
Looks like I could implement the single-sourcing the package version using method 1 of: https://packaging.python.org/guides/single-sourcing-package-version/

Trying to close again.
